---
- name: Windows Test Playbook
  hosts: all
  tasks:
    - name: Remote Execute the mqsc files
      ansible.windows.win_shell: |
        hostname
        Get-Date
      register: scriptoutput

    - name: Script output
      debug: var=case1output.stdout
