---
- name: Windows Test Playbook
  hosts: all
  tasks:
    - name: Remote Execute the mqsc files
      win_shell: |
        hostname
        Get-Date
      register: scriptoutput

    - name: Script output
      debug: var=scriptoutput.stdout
