---
- name: Windows Test Playbook
  hosts: all
  tasks:
    - name: Remote Execute the mqsc files
      win_shell: |
        hostname
        Get-Date
      register: scriptoutput

    - debug:
        var: "scriptoutput.stdout_lines"
      changed_when: False
